version: '3.3'

services:
  app-agenda:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    environment:
      - JAVA_OPTS=-Dspring.profiles.active=prod
      - TZ=America/Sao_Paulo
    container_name: agenda
    networks:
      - backend-toten_totem-network

networks:
  backend-toten_totem-network:
    external: true
